# https://numtide.github.io/devshell
[devshell]
packages = [
    "rust-tauri-android",
    "cargo-tauri-beta",
    "trunk",
    "wasm-bindgen-cli",
    "android-sdk",
    "gradle",
    "jdk17",
]

[[env]]
name =  "ANDROID_HOME"
eval = "$DEVSHELL_DIR/share/android-sdk"
[[env]]
name = "ANDROID_SDK_ROOT"
eval = "$ANDROID_HOME"
[[env]]
name = "NDK_HOME"
eval = "$ANDROID_HOME/ndk/25.2.9519653"
[[env]]
name = "JAVA_HOME"
eval = "$DEVSHELL_DIR/zulu-17.jdk/Contents/Home"
